"""Identify and freeze the car files deployed by a development sync."""

import fnmatch
import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path

VERSION_PATH = "system/version.toml"


def snapshot_car(source, destination, excludes):
    def ignore(directory, names):
        relative = Path(directory).relative_to(source)
        return [
            name
            for name in names
            if (relative / name).as_posix() == VERSION_PATH
            or any(fnmatch.fnmatch(name, pattern.rstrip("/")) for pattern in excludes)
        ]

    shutil.copytree(source, destination, symlinks=True, ignore=ignore)


def snapshot_checksum(root):
    """Hash sorted paths, contents/link targets, and executable permission bits."""
    digest = hashlib.sha256()
    for path in sorted(Path(root).rglob("*")):
        if not path.is_symlink() and not path.is_file():
            continue
        name = path.relative_to(root).as_posix().encode()
        content = os.readlink(path).encode() if path.is_symlink() else path.read_bytes()
        kind = b"link" if path.is_symlink() else b"file"
        mode = b"" if path.is_symlink() else str(path.stat().st_mode & 0o111).encode()
        for value in (name, kind, mode, content):
            digest.update(len(value).to_bytes(8, "big"))
            digest.update(value)
    return digest.hexdigest()


def git_version(repository):
    def git(*arguments):
        return subprocess.run(
            ["git", *arguments],
            cwd=repository,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()

    return {
        "version": git("describe", "--tags", "--match", "v[0-9]*", "--always"),
        "commit": git("rev-parse", "HEAD"),
        "dirty": bool(git("status", "--porcelain", "--untracked-files=normal")),
    }


def version_toml(record):
    lines = ["# Generated by the car sync tool; do not edit.", "[code]"]
    for key, value in record.items():
        encoded = str(value).lower() if isinstance(value, bool) else json.dumps(value)
        lines.append(f"{key} = {encoded}")
    return "\n".join(lines) + "\n"


# Executed on the Pi via SSH. os.replace publishes one complete record atomically.
PUBLISH_SCRIPT = """import os, pathlib, sys, tempfile
root = pathlib.Path(sys.argv[1])
system = root / "system"
if root.is_symlink() or system.is_symlink():
    raise ValueError("Version destination must not be a symlink")
with tempfile.NamedTemporaryFile(mode="w", dir=system, delete=False) as stream:
    temporary = pathlib.Path(stream.name)
    stream.write(sys.stdin.read())
try:
    temporary.chmod(0o644)
    os.replace(temporary, system / "version.toml")
finally:
    temporary.unlink(missing_ok=True)
"""
